language: python
python:
  - '2.7'
before_install:
  - openssl aes-256-cbc -K $encrypted_27c6f75aee4e_key -iv $encrypted_27c6f75aee4e_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval `ssh-agent -s`
  - ssh-add github_deploy_key
install:
  - git clone -b init git@github.com:bridgenow/bridgenow.github.io.git ../home
  - git clone -b init git@github.com:bridgenow/template.git ../template
  - pip install -r ../template/requirements.txt
script:
  - python build.py
  - python deploy.py
env:
  global:
  - COMMIT_AUTHOR_EMAIL: "mark.dessain@gmail.com"
  - COMMIT_AUTHOR_NAME: "Travis Job"
