language: python
python:
  - '2.7'
before_install:
  - openssl aes-256-cbc -K $encrypted_27c6f75aee4e_key -iv $encrypted_27c6f75aee4e_iv -in keys/github_deploy_key.enc -out keys/github_deploy_key -d
  - chmod 600 keys/github_deploy_key
  - eval `ssh-agent -s`
  - ssh-add keys/github_deploy_key
install:
  - git clone git@github.com:bridgenow/bridgenow.github.io.git ../home
  - git clone git@github.com:bridgenow/template.git ../template
  - pip install -r ../template/requirements.txt
script:
  - python ../template/scripts/build.py
  - echo $TRAVIS_BRANCH
  - [ "${TRAVIS_BRANCH}" = "init" ] && python ../template/scripts/build.py || false
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "mark.dessain@gmail.com"
    - COMMIT_AUTHOR_NAME: "Travis Job"
